DROP DATABASE todos IF EXISTS;

CREATE DATABASE todos;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NUll UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE tasks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    user_id INT UNSIGNED NOT NULL,
    tittle VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    completed BOOLEAN NOT NULL, 
    due_date DATETIME NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users(id)
        ON UPDATE CASCADE 
        ON DELETE CASCADE
);